### ISSUE TITLE
PageQualityScorerReadability only looks inside <p> tags when counting words in sentences

### ISSUE THREAD

**Issue by drorsnir** [nischayn22/PageQuality#12]
But sentences can be inside other block elements, such as `<li>`

**Comment by nischayn22** [comment]
Any other tags you want me to add?

**Comment by drorsnir** [comment]
I think basically `<div>` and `<td>` tags can be regarded as paragraphs, while an `<li>` is a single sentence.

**Comment by nischayn22** [comment]
I am not sure how to consider <div> tags as they might have <p> tags within them, it could lead to double counting the text. Do you think we should consider a page as an example to test it out?

**Comment by drorsnir** [comment]
You are right to consider that. Looking at one of our most popular pages, Minimum Wage:
kolzchut.org.il/he/שכר_מינימום

I see `<div>` tags mainly where I insert them using templates, and then you can have nesting tags, either a `<div>`, `<ul>` or `<p>`.

A `<td>` tag can also hold any of those.

One example of nesting `<div>`s is fine:
`<div class="wr-note-text" data-raofz="17"><div class="text-body" data-raofz="17">עובד בחצי משרה זכאי לשכר מינימום בגובה  2,650 ש"ח (לפי החישוב: 1/2 × 5,300).</div></div>`

Another example of nesting `<div>`, including even a `<ul>`:
```
<div class="wr-note clearfix wr-please-note"><div class="wr-note-icon-wrapper"><div class="wr-note-icon"></div><div class="wr-note-icon-text><span class="text-nowrap">שימו לב</span></div></div><div class="wr-note-text"><div class="text-body">
<ul>
<li>1</li>
<li>2</li>
</ul></div></div></div>
```

And possibly even something like this:
```
<div class="wr-note-text">
	<div class="text-title">גובה שכר המינימום לשעה בעקבות</div>
	<div class="text-body">bla bla bla<br>
		bla bla black
		<ol>
			<li>1</li>
			<li>2</li>
		</ol>
	</div>
</div>
```

It looks to me like for every paragraph-level tag you will have to go deep inside, right? When entering a `<div>`, e.g. `<div class="wr-note-text">`,  you will have to go to the next level, and see two new "paragraphs":
- .text-title, which you count and are done
- .text-body, which itself contains two sentences (because of the `<br>` and one additional "paragraph" (the `<ol>`).

What do you think?

**Comment by nischayn22** [comment]
Strangely I never received a notification for your reply.

I don't think it makes sense to make the code class-aware, instead, I would recommend that I consider an entire div as one paragraph if there are no <div>, <p> or <li> tags nested in it. 

Additionally I would consider each <li> as a paragraph. Does that make sense?

**Comment by drorsnir** [comment]
Sorry, you should escape tags inside code blocks, or else they are  rendered and I'm not sure what they are.

I wasn't suggesting that you take the classes themselves into consideration, just demonstrating the recursive nature of the process using a specific example.

I think what you wrote is that you will conside a `<div>` as one paragraph if there are no other `<div>`, `<p>` or `<li>` tags in it.

So, otherwise you will simply ignore it, and so the audit will check its children for the same condition? That's actually much better and simpler than my idea! Is there any reason not to implement the same for `<li>`? They are also allowed to contain other block elements.

**Comment by nischayn22** [comment]
Kindly try out this new algorithm and let me know if it works.

https://github.com/nischayn22/PageQuality/commit/6385d596c291257f7717cdc3bdf5537793465d38

**Comment by drorsnir** [comment]
1. This is better! I think you will have to special-case the `<li>`, as it's only paragraph-like __if__ it has the relevant child nodes (`<div>`, `<p>` or `<li>`) .
As it currently stands,  you treat it both as a sentence and as a paragraph at the same time, and get warning for both.

2. Something with the loops isn't working right - I'm getting multiples of the same sentence:
![image](https://user-images.githubusercontent.com/3416107/158060730-2f01cb43-67c6-4d06-b222-c977f25d8775.png)

3. Emphasis lines now hit both `emphasis_line_length` and `sentence_length` audits

**Comment by nischayn22** [comment]
1. is fixed by https://github.com/nischayn22/PageQuality/commit/e94321b832109582409e6f3a33ec88e833894b84
2. Can you please share the link to the page
3. I think handling this would mess up the code, can we either just remove emphasis_line_length or live with two errors?

**Comment by drorsnir** [comment]
1. Great
2. I'm sending you a few test cases I built for the current audits - you can import them directly into a wiki. Test case 3 exhibits this issue of repeat warning for the same sentence.
3. This could be an issue if the emphasis line audit becomes more lenient than the sentence_length audit - you would get no error for emphasis_line_length but still get an error for sentence_length. Maybe we should have a standard "ignore-audit-[audit name]" data attribute for elements, and then adapt removeIgnoredElements() and getElementsByClassName() to match those? Anyway, let's leave it for later and finish everything else.

**Comment by nischayn22** [comment]
https://github.com/nischayn22/PageQuality/commit/cd83d1b972ac975f06154e59971d62351ada7dc2 fixes these.

**Comment by drorsnir** [comment]
Issue resolved.
